module.exports = {
  progressBar: document.getElementById('progress-value'),
  folderButton: document.getElementById('open-folder'),
  pauseButton: document.getElementById('pause'),
  playButton: document.getElementById('play'),
  forwardButton: document.getElementById('forward'),
  backwardButton: document.getElementById('backward'),
  shuffleButton: document.getElementById('shuffle'),
  shuffleButtonActive: document.getElementById('shuffle-active'),
  repeatButton: document.getElementById('repeat'),
  repeatButtonActive: document.getElementById('repeat-active'),
  sortByNameButton: document.getElementById('by-name'),
  sortByAlbumButton: document.getElementById('by-album'),
  sortByArtistButton: document.getElementById('by-artist'),
  base64String: undefined,
  globalFiles: undefined,
  originalGlobalFiles: undefined,
  currentFileInList: undefined,
  index: undefined,
  isOnRepeat: false
};
